#!/usr/bin/env python3
"""
build-html.py — Markdown → HTML 转换器
用法: python build-html.py topics/ota-firmware-upgrade/
      python build-html.py --all
---
EM-SKILL 学习模式插件 · tools/build-html.py
归属: plugins/learning/ (与 plugins/embedded/ 同构)
"""

import markdown, re, sys
from pathlib import Path
from datetime import datetime

MD_EXTENSIONS = ['tables', 'fenced_code', 'toc', 'footnotes', 'md_in_html', 'attr_list']

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} | EM-SKILL</title>
<style>
:root{{--bg:#0d1117;--fg:#c9d1d9;--accent:#58a6ff;--card:#161b22;--border:#30363d}}
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:system-ui,sans-serif;background:var(--bg);color:var(--fg);line-height:1.7;max-width:900px;margin:0 auto;padding:40px 20px}}
h1{{color:var(--accent);font-size:2em;margin-bottom:.3em}}
h2{{color:var(--accent);font-size:1.5em;margin:1.5em 0 .5em;border-bottom:1px solid var(--border);padding-bottom:.3em}}
h3{{color:#7ee787;font-size:1.2em;margin:1.2em 0 .4em}}
blockquote{{background:var(--card);border-left:4px solid #d29922;padding:12px 16px;margin:1em 0;border-radius:0 8px 8px 0}}
blockquote strong{{color:#f85149}}
code{{background:#21262d;padding:2px 6px;border-radius:4px;font-family:monospace;font-size:.9em}}
pre{{background:#21262d;padding:16px;border-radius:8px;overflow-x:auto;margin:1em 0}}
pre code{{padding:0;background:none}}
table{{width:100%;border-collapse:collapse;margin:1em 0;font-size:.9em}}
th,td{{padding:10px 12px;text-align:left;border-bottom:1px solid var(--border)}}
th{{color:var(--accent);font-weight:600}}
tr:hover{{background:rgba(88,166,255,.05)}}
a{{color:var(--accent);text-decoration:none}}
a:hover{{text-decoration:underline}}
.video{{background:var(--card);border:1px solid var(--border);border-radius:12px;padding:16px;margin:1em 0}}
.video video{{width:100%;border-radius:8px}}
.footer{{margin-top:3em;padding-top:1em;border-top:1px solid var(--border);font-size:.85em;color:#8b949e}}
.mermaid{{background:var(--card);border-radius:8px;padding:16px;margin:1em 0}}
</style>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<script>mermaid.initialize({{startOnLoad:true,theme:'dark'}});</script>
</head>
<body>
{content}
<div class="footer">
<p>Generated by EM-SKILL v4.1 | {timestamp}</p>
<p>Source: <a href="{source}">Markdown</a> | <a href="{research}">Research</a></p>
</div>
</body>
</html>"""

def convert(topic_dir: Path) -> str:
    readme = topic_dir / "README.md"
    if not readme.exists(): raise FileNotFoundError(f"README.md not found in {topic_dir}")
    with open(readme, 'r', encoding='utf-8') as f: md = f.read()
    html = markdown.markdown(md, extensions=MD_EXTENSIONS)
    # 视频嵌入: [video:url] -> <video>
    html = re.sub(r'\[video:(.*?)\]', lambda m: f'<div class="video"><video controls><source src="{m.group(1)}" type="video/mp4"></video></div>', html)
    title = re.search(r'<h1>(.*?)</h1>', html)
    return HTML_TEMPLATE.format(
        title=title.group(1) if title else topic_dir.name,
        content=html, timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
        source=f"{topic_dir.name}/README.md", research=f"{topic_dir.name}/research/"
    )

def main():
    if len(sys.argv) < 2: print("Usage: build-html.py <topic-dir> | --all"); sys.exit(1)
    if sys.argv[1] == '--all':
        for d in Path('.em/learning/topics').iterdir():
            if d.is_dir():
                out = d / "index.html"
                with open(out, 'w', encoding='utf-8') as f: f.write(convert(d))
                print(f"Built: {out}")
    else:
        d = Path(sys.argv[1]); out = d / "index.html"
        with open(out, 'w', encoding='utf-8') as f: f.write(convert(d))
        print(f"Built: {out}")

if __name__ == '__main__': main()